### ISSUE TITLE
Erros encontrados no cadastro do pet

### ISSUE THREAD

**Issue by TiagoSF18** [yurry0/syspetWeb#46]
- O sistema realiza o cadastro duplicado de pets.

- O sistema possibilita a inserção de valores negativos para (Idade, altura e peso).

- O sistema conclui o cadastro mesmo com campos vazios.
- O sistema não conclui o cadastro do pet se ele não tiver foto.
- O sistema não realiza tratamento de dados inseridos pelo usuário. Ex.: O sistema  reconhece aceita caracteres especiais como  “raça” do pet.
- O sistema não retorna mensagem de “Dados inválidos” no cadastro com erros do pet

**Comment by yurry0** [comment]
Boa parte dos bugs corrigidos, somente algumas ressalvas:
_O sistema realiza o cadastro duplicado de pets._
_O sistema não conclui o cadastro do pet se ele não tiver foto._

- Por falta de tempo, não foi possível atender a esses pontos em específico. Eles se provaram mais complexos do que eu esperava, então vai ficar pra uma próxima oportunidade.
