### ISSUE TITLE
Erros encontrados no Cadastro de Clientes

### ISSUE THREAD

**Issue by TiagoSF18** [yurry0/syspetWeb#47]
- O cadastro do cliente não é concluído ao selecionar o botão “Adicionar”. É exibido o seguinte erro:
 Not FoundThe requested URL was not found on this server.Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.2 Server at localhost Port 80

- O sistema não realiza tratamento nos dados inseridos, Ex.: limite de caracteres, restrições à caracteres especiais, preenchimento de campo apenas com (SPACE)..
 
- O sistema não exibe a mensagem: "Cliente cadastrado com sucesso." após o cadastro realizado corretamente;
- O sistema não exibe a mensagem: " Dados inválidos." após a tentativa de cadastro inválido;

- O campo “Cidade” aceita caracteres especiais para compor um nome da cidade;
- O campo “RG” não tem limite de caracteres e aceita letras e caracteres especiais;
- O Sistema não verifica o CEP, bem como limite de caracteres e caracteres especiais;
- O campo “Endereço” aceita números e caracteres especiais como suficiente para compor um endereço;
- O campo “Bairro” aceita números e caracteres especiais como suficiente para compor um Bairrro;
- O campo “Email” aceita email já cadastrado no sistema;
- O campo “Nome” aceita números e caracteres especiais como suficiente para compor um Nome;

**Comment by yurry0** [comment]
Todos os pontos foram solucionados.
